esphome:
  name: esp8266_temperature_sensors
  platform: ESP8266
  board: nodemcuv2
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
  # Set this to the IP of the ESP
    static_ip: 192.168.1.200 # replace with your IP address
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.1.254 # replace with your router IP address
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
  fast_connect: true

# Enable the OneWire component
dallas:
  - pin: D4
    update_interval: 15s

# Enable the sensor component
sensor:
  - platform: dallas
    address: 0x473c01f095294e28
    name: "Living Room"
    accuracy_decimals: 2
    filters:
    - clamp:
        min_value: 0
        max_value: 45
        ignore_out_of_range: true

  - platform: dallas
    address: 0x4f3c01f0954d7b28
    name: "Downstairs Hallway"
    accuracy_decimals: 2
    filters:
    - clamp:
        min_value: 0
        max_value: 45
        ignore_out_of_range: true

  - platform: dallas
    address: 0x00c90bb00164ff28
    name: "Downstairs Bedroom"
    accuracy_decimals: 2
    filters:
    - clamp:
        min_value: 0
        max_value: 45
        ignore_out_of_range: true

  - platform: dallas
    address: 0xe7ac00b40164ff28
    name: "Main Bedroom"
    accuracy_decimals: 2
    filters:
    - clamp:
        min_value: 0
        max_value: 45
        ignore_out_of_range: true
  
  - platform: dallas
    address: 0x433ce10457da7d28
    name: "Garage"
    accuracy_decimals: 2
    filters:
    - clamp:
        min_value: -10
        max_value: 45
        ignore_out_of_range: true
  
  - platform: dallas
    address: 0x633ce1e38026ae28
    name: "Garage Fridge"
    accuracy_decimals: 2  
    filters:
    - clamp:
        min_value: -10
        max_value: 45
        ignore_out_of_range: true
  
  - platform: dallas
    address: 0xc03ce1045794c728
    name: "Garage Freezer"
    accuracy_decimals: 2  
    filters:
    - clamp:
        min_value: -100
        max_value: 45
        ignore_out_of_range: true


# Enable the ESPHome API
api:
  reboot_timeout: 15min
#
ota:
#
logger:
  level: debug
#
web_server:
  port: 80
#
time:
  - platform: homeassistant
    id: homeassistant_time

